### ISSUE TITLE
PagerDuty::Users::User - Sub properties aren't being updated

### ISSUE THREAD

**Issue by kddejong** [aws-ia/cloudformation-pagerduty-resource-providers#20]
`contact_methods` and `notification_rules` are not updated on an update call.  According to the docs those aren't specified input values: https://developer.pagerduty.com/api-reference/ce6799fc6191a-update-a-user.  

Using the API directly when you specify these values they are ignored and the original values are sent back.

**Comment by lukiwlosek** [comment]
This was done to pass the contract tests initially, because `HtmlUrl` prop were returned as null for `contact_methods` and `notification_rules`, these do not generate unfortunately so I have deleted it from the schema in this [PR](https://github.com/aws-ia/cloudformation-pagerduty-resource-providers/pull/22).

**Comment by kddejong** [comment]
I was finding more discrepancies than that.  update user doesn't take a property for `contact_methods` plus the ID used in a property like `contact_methods` looks to be auto-generated from PagerDuty.

**Comment by lukiwlosek** [comment]
I have updated the PR so the Id's are marked as readOnlyProperties in the schema and rerun the tests.

**Comment by joshuadeanhall** [comment]
#22 has been merged and the schema should now reflect that `contact_methods` and `notification_rules` are `readOnlyProperties`

Contract Testing and usage of the resource should be fixed for this problem.
