### ISSUE TITLE
More readOnlyProperties for ContactMethods and NotificationRules

### ISSUE THREAD

**Issue by kddejong** [aws-ia/cloudformation-pagerduty-resource-providers#23]
No part of ContactMethods and NotificationRules can be updated using the https://developer.pagerduty.com/api-reference/ce6799fc6191a-update-a-user 

I think we should make all properties in those two sections as read only

**Comment by lukiwlosek** [comment]
Potential fix in [PR](https://github.com/aws-ia/cloudformation-pagerduty-resource-providers/pull/24), I think this might be an issue with ctv2 but in order to pass it I had to add readOnlyProps: 
`   "/properties/ContactMethods/*/Id",
    "/properties/ContactMethods/*/Type",
    "/properties/ContactMethods/*/Summary",
    "/properties/NotificationRules/*/Id",
    "/properties/NotificationRules/*/Type",
    "/properties/NotificationRules/*/Summary"`
And deleted the required fields from `NotificationRules` and `ContractMethods` as adding `"/properties/NotificationRules/*/Summary"` was causing errors,

After doing so I also tried: 
`   "/properties/ContactMethods",
    "/properties/NotificationRules"`
but this always seems to fail even when I log out the readHandler the props do match

Let me know if this is satisfactory and any tips on how to get the latter working.
